var str = {
    invite_user_id_placeholder: "referrer's code (optional)",
    username_placeholder: "Username",
    username_error: "Please enter your username. between 4 and 20 characters.",
    mobile_placeholder: "Mobile",
    mobile_error: "Please enter your mobile.",
    email_placeholder: "Email",
    email_error: "Please enter your email.",
    password_placeholder: "Password",
    password_error: "Please enter your password. between 6 and 20 characters.",
    password_confirm_placeholder: "Confirm Password",
    password_confirm_error: "Please confirm your password.",
    verify_code_placeholder: "Verification Code",
    verify_code_error: "Please enter the Verification Code.",
};
